/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juegodedados;

/**
 *
 * @author estudiantes
 */
public class Gráfica extends javax.swing.JFrame {

    Dado d1;
    Dado d2;
    
  
    

    /**
     * Creates new form Gráfica
     */
    public Gráfica() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pantalladado1 = new javax.swing.JTextField();
        Pantalladado2 = new javax.swing.JTextField();
        VLanzar = new javax.swing.JButton();
        PantallaApuesta = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        PantallaBilletera = new javax.swing.JTextField();
        PantallaMensaje = new javax.swing.JTextField();
        VApuesta = new javax.swing.JLabel();
        VBilletra = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Pantalladado1.setText("jTextField1");

        Pantalladado2.setText("jTextField2");

        VLanzar.setText("LANZAR");
        VLanzar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VLanzarMouseClicked(evt);
            }
        });
        VLanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VLanzarActionPerformed(evt);
            }
        });

        PantallaApuesta.setText("jTextField2");
        PantallaApuesta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PantallaApuestaKeyPressed(evt);
            }
        });

        jTextField4.setText("jTextField2");

        PantallaBilletera.setText("jTextField5");
        PantallaBilletera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PantallaBilleteraActionPerformed(evt);
            }
        });

        PantallaMensaje.setText("jTextField6");
        PantallaMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PantallaMensajeActionPerformed(evt);
            }
        });

        VApuesta.setText("Apuesta");

        VBilletra.setText("Billetera");

        jLabel3.setText("Mensaje");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(Pantalladado1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Pantalladado2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel3)
                        .addGap(23, 23, 23)
                        .addComponent(PantallaMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(VApuesta)
                            .addComponent(VBilletra))
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PantallaBilletera, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(PantallaApuesta))))
                .addGap(0, 126, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(VLanzar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(507, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Pantalladado2, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(Pantalladado1))
                .addGap(5, 5, 5)
                .addComponent(VLanzar)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PantallaApuesta)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 32, Short.MAX_VALUE)
                        .addComponent(VApuesta)
                        .addGap(17, 17, 17)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(79, 79, 79))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PantallaBilletera, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VBilletra))
                        .addGap(18, 18, 18)
                        .addComponent(PantallaMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(369, Short.MAX_VALUE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(120, 120, 120)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PantallaMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PantallaMensajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PantallaMensajeActionPerformed

    private void VLanzarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VLanzarMouseClicked
      if (Jugador.apuesta!=0){ 
        d1.lanzar();
        d2.lanzar();
        
        Pantalladado1.setText(Integer.toString(d1.nùmero));
        Pantalladado2.setText(Integer.toString(d2.nùmero));        

} 
// TODO add your handling code here:
    }//GEN-LAST:event_VLanzarMouseClicked

    private void VLanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VLanzarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VLanzarActionPerformed

    private void PantallaBilleteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PantallaBilleteraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PantallaBilleteraActionPerformed

    private void PantallaApuestaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PantallaApuestaKeyPressed
    
    }//GEN-LAST:event_PantallaApuestaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gráfica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gráfica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gráfica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gráfica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Gráfica().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PantallaApuesta;
    private javax.swing.JTextField PantallaBilletera;
    private javax.swing.JTextField PantallaMensaje;
    private javax.swing.JTextField Pantalladado1;
    private javax.swing.JTextField Pantalladado2;
    private javax.swing.JLabel VApuesta;
    private javax.swing.JLabel VBilletra;
    private javax.swing.JButton VLanzar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
